name:                ask-dice
version:             0.1.0.0
github:              "yurry/ask-dice"
license:             BSD3
author:              "Yuri Gorshkov"
maintainer:          "example@example.com"
copyright:           "2018 Yuri Gorshkov"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/ask-dice#readme>

dependencies:
- base >= 4.7 && < 5
- Spock >=0.11
- mtl
- text

library:
  source-dirs: src

executables:
  ask-dice-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ask-dice

tests:
  ask-dice-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ask-dice
